stages:
  data_ingestion:
    cmd: python src/data_ingestion.py
    deps:
    - src/data_ingestion.py
    params:
    - data_ingestion.test_size
    outs:
    - data/raw

  data_preprocessing:
    cmd: python src/data_preprocessing.py
    deps:
    - src/data_preprocessing.py
    - data/raw
    outs:
    - data/interim


  feature_eng:
    cmd: python src/feature_eng.py
    deps:
    - src/feature_eng.py
    - data/interim
    params:
    - feature_eng.max_features
    outs:
    - data/processed

  model_training:
    cmd: python src/model_training.py
    deps:
    - src/model_training.py
    - data/processed
    params:
    - model_training.n_estimators
    - model_training.random_state
    outs:
    - models/model.pkl

  model_evaluation:
    cmd: python src/model_evaluation.py
    deps:
    - src/model_evaluation.py
    - models/model.pkl
    metrics:
    - reports/metrics.json
params:
- dvclive/params.yaml
metrics:
- dvclive/metrics.json
plots:
- dvclive/plots/metrics:
    x: step
